CREATE TABLE IF NOT EXISTS "PopupTriggerConfig" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "configJson" TEXT NOT NULL,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
