# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "336aed7a0572b8179610ed2e5698cd78"
application_url = "https://shopify-funnel-control.tigerbrands-funnel.workers.dev/admin/"
embedded = true
name = "Funnel Builder"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,read_customer_events,read_customers,write_customers,read_orders,read_reports,read_products,read_discounts,write_discounts,read_pixels,write_pixels"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["orders/paid", "orders/updated"]
uri = "https://shopify-funnel-control.tigerbrands-funnel.workers.dev/webhooks/shopify"

[app_proxy]
url = "https://shopify-funnel-control.tigerbrands-funnel.workers.dev/apps/funnels"
subpath = "funnels"
prefix = "apps"
