"""QA the delegated admin dashboard.

The dashboard was generated by a cheap model from a spec; this checks it
actually does what the spec said, including the security requirement.
"""
import functools
import http.server
import pathlib
import socketserver
import sys
import threading

from playwright.sync_api import sync_playwright

ADMIN_DIR = pathlib.Path(__file__).resolve().parents[1] / "admin"
results = []


def serve(directory):
    """The dashboard fetches absolute paths like /api/ai-steps. Over file://
    those resolve to file:///api/... and cannot be intercepted, so the page has
    to be served over HTTP for the network tests to mean anything."""
    handler = functools.partial(http.server.SimpleHTTPRequestHandler,
                                directory=str(directory))
    httpd = socketserver.TCPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd, f"http://127.0.0.1:{httpd.server_address[1]}/dashboard.html"


def check(name, ok, detail=""):
    results.append((name, ok, detail))
    line = ("  PASS  " if ok else "  FAIL  ") + name + (f"  [{detail}]" if detail else "")
    sys.stdout.buffer.write(line.encode("utf-8", "replace") + b"\n")
    sys.stdout.flush()


STEPS_FIXTURE = {
    "days": 14, "conversations": 42,
    "steps": [
        {"stepId": "root_choice", "stepType": "ask", "shown": 100, "answered": 80,
         "exits": 5, "dropOffRate": 20.0, "avgDwellSeconds": 4.2,
         "choices": [{"label": "הגוון", "count": 50}, {"label": "מחיר", "count": 30}],
         # deliberately hostile: shopper free text is attacker-controlled
         "freeTexts": ["<img src=x onerror=window.__XSS=1>", "רגיל"]},
        {"stepId": "shade_photo", "stepType": "photo", "shown": 60, "answered": 20,
         "exits": 10, "dropOffRate": 66.7, "avgDwellSeconds": 9.1,
         "choices": [{"label": "דילוג", "count": 20}], "freeTexts": []},
    ],
}


def run():
    httpd, PAGE = serve(ADMIN_DIR)
    with sync_playwright() as p:
        b = p.chromium.launch()
        page = b.new_page(viewport={"width": 1200, "height": 900})
        page.add_init_script("window.shopify = { idToken: () => Promise.resolve('qa-session-token') };")
        page.route("https://cdn.shopify.com/shopifycloud/app-bridge.js", lambda r: r.fulfill(
            status=200, content_type="application/javascript", body=""))

        auth_headers = []
        def on_steps(route):
            auth_headers.append(route.request.headers.get("authorization", ""))
            route.fulfill(status=200, content_type="application/json",
                          body=__import__("json").dumps(STEPS_FIXTURE))
        page.route("**/api/ai-steps*", on_steps)

        def on_models(route):
            auth_headers.append(route.request.headers.get("authorization", ""))
            route.fulfill(status=200, content_type="application/json", body=__import__("json").dumps({
                "mode": "fallback_ladder", "deadlineMs": 8000,
                "models": ["z-ai/glm-5.3-flash", "minimax/minimax-m2.7:free"]
            }))
        page.route("**/api/ai-models", on_models)

        errors = []
        page.on("pageerror", lambda e: errors.append(str(e)))
        page.goto(PAGE)
        page.wait_for_timeout(500)
        check("page loads with no JS errors", not errors, "; ".join(errors)[:120])

        tabs = page.eval_on_selector_all("button, [role=tab], .tab", "e => e.map(x => x.textContent.trim())")
        check("three tabs present", sum(t in ("טריגרים", "שלבי שיחה", "מודלים") for t in tabs) == 3, str(tabs[:6]))

        # ---- tab 1: triggers ----
        numbers = page.eval_on_selector_all("input[type=number]", "e => e.length")
        check("trigger form renders numeric fields", numbers >= 12, f"{numbers} fields")
        val = page.eval_on_selector("input[type=number]", "e => e.value")
        check("fields are pre-filled with defaults", val not in ("", None), str(val))

        # ---- tab 2: conversation steps ----
        page.click("text=שלבי שיחה")
        page.wait_for_timeout(700)
        body = page.inner_text("body")
        check("step data renders", "root_choice" in body and "shade_photo" in body)
        check("conversation total shown", "42" in body)
        check("drop-off percentage rendered", "66.7" in body or "66" in body)
        check("admin API receives a Shopify session token",
              auth_headers and auth_headers[-1] == "Bearer qa-session-token", str(auth_headers))

        # the security requirement
        page.wait_for_timeout(300)
        xss = page.evaluate("() => window.__XSS === 1")
        check("hostile shopper free text is NOT executed", xss is False)
        imgs = page.eval_on_selector_all("details img, img[src='x']", "e => e.length")
        check("free text is not injected as HTML", imgs == 0, f"{imgs} injected nodes")
        # Free texts sit inside a collapsed <details>, so expand before reading.
        page.evaluate("() => document.querySelectorAll('details').forEach(d => d.open = true)")
        page.wait_for_timeout(200)
        expanded = page.inner_text("body")
        check("hostile string is shown as literal text",
              "<img src=x" in expanded or "onerror" in expanded,
              expanded[expanded.find("onerror") - 20:][:60] if "onerror" in expanded else "not found")

        # ---- tab 3: read-only server model configuration ----
        page.click("text=מודלים")
        page.wait_for_timeout(400)
        body2 = page.inner_text("body")
        check("active model ladder is loaded from the authenticated backend",
              "glm-5.3-flash" in body2 and "minimax" in body2, body2[-180:])
        check("dashboard no longer offers a fake model-split save",
              "/api/model-split" not in page.content())
        check("model API receives a Shopify session token",
              auth_headers and auth_headers[-1] == "Bearer qa-session-token", str(auth_headers))

        b.close()
    httpd.shutdown()


if __name__ == "__main__":
    run()
    failed = [r for r in results if not r[1]]
    print(f"\n{len(results) - len(failed)}/{len(results)} passed")
    sys.exit(1 if failed else 0)
